# Generated by Django 5.2.8 on 2025-11-09 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sites",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RackConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("config_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        db_column="site_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rack_configurations",
                        to="api.site",
                    ),
                ),
            ],
            options={
                "db_table": "rack_configurations",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["site"], name="rack_config_site_id_417903_idx"
                    ),
                    models.Index(fields=["name"], name="rack_config_name_e373b9_idx"),
                ],
                "unique_together": {("site", "name")},
            },
        ),
    ]
