# Generated by Django 5.2.8 on 2025-11-09 01:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('ru_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('power_draw', models.IntegerField(help_text='Power consumption in watts', validators=[django.core.validators.MinValueValidator(0)])),
                ('color', models.CharField(default='#000000', help_text='Hex color code for display', max_length=7)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'devices',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['device_id'], name='devices_device__c4b5e4_idx'), models.Index(fields=['category'], name='devices_categor_13d452_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ru_height', models.IntegerField(default=42, validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(db_column='site_id', on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='api.site')),
            ],
            options={
                'db_table': 'racks',
                'ordering': ['site', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RackDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(help_text='Starting RU position (1-based)', validators=[django.core.validators.MinValueValidator(1)])),
                ('instance_name', models.CharField(blank=True, help_text='Custom name for this device instance', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, related_name='rack_placements', to='api.device')),
                ('rack', models.ForeignKey(db_column='rack_id', on_delete=django.db.models.deletion.CASCADE, related_name='rack_devices', to='api.rack')),
            ],
            options={
                'db_table': 'rack_devices',
                'ordering': ['rack', 'position'],
            },
        ),
        migrations.AddIndex(
            model_name='rack',
            index=models.Index(fields=['site'], name='racks_site_id_b1bdc2_idx'),
        ),
        migrations.AddIndex(
            model_name='rack',
            index=models.Index(fields=['name'], name='racks_name_9310b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rack',
            unique_together={('site', 'name')},
        ),
        migrations.AddIndex(
            model_name='rackdevice',
            index=models.Index(fields=['rack'], name='rack_device_rack_id_6f2e6f_idx'),
        ),
        migrations.AddIndex(
            model_name='rackdevice',
            index=models.Index(fields=['device'], name='rack_device_device__2c6fd5_idx'),
        ),
        migrations.AddIndex(
            model_name='rackdevice',
            index=models.Index(fields=['position'], name='rack_device_positio_d8d19f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rackdevice',
            unique_together={('rack', 'position')},
        ),
    ]
