# Generated by Django 5.2.8 on 2025-11-09 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_device_rack_rackdevice_rack_racks_site_id_b1bdc2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.CharField(db_index=True, help_text='Base64-encoded credential ID', max_length=255, unique=True)),
                ('public_key', models.TextField(help_text='Base64-encoded public key')),
                ('sign_count', models.IntegerField(default=0, help_text='Signature counter for replay protection')),
                ('transports', models.JSONField(blank=True, default=list, help_text='Supported transports (usb, nfc, ble, internal)')),
                ('aaguid', models.CharField(blank=True, help_text='Authenticator AAGUID', max_length=255)),
                ('name', models.CharField(help_text='User-friendly name for this passkey', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passkeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'passkeys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='passkeys_user_id_2a1654_idx'), models.Index(fields=['credential_id'], name='passkeys_credent_29d9a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='PasskeyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.CharField(help_text='Base64-encoded challenge', max_length=255)),
                ('challenge_type', models.CharField(choices=[('registration', 'Registration'), ('authentication', 'Authentication')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Challenge expiration time')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passkey_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'passkey_challenges',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='passkey_cha_user_id_fa98a3_idx'), models.Index(fields=['challenge'], name='passkey_cha_challen_80e08f_idx'), models.Index(fields=['expires_at'], name='passkey_cha_expires_29d42f_idx')],
            },
        ),
    ]
