# Generated by Django 5.2.8 on 2025-11-11 00:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_uuid_to_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'device_groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HardwareProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hardware_providers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='device_group',
            field=models.ForeignKey(blank=True, db_column='device_group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='api.devicegroup'),
        ),
        migrations.AddField(
            model_name='device',
            name='provider',
            field=models.ForeignKey(blank=True, db_column='provider_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='api.hardwareprovider'),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('power', 'Power'), ('cooling', 'Cooling'), ('network', 'Network')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, help_text='Physical location description', max_length=255, null=True)),
                ('power_capacity', models.IntegerField(default=0, help_text='Power capacity in watts', validators=[django.core.validators.MinValueValidator(0)])),
                ('power_ports_capacity', models.IntegerField(default=0, help_text='Number of power ports available (for PDUs)', validators=[django.core.validators.MinValueValidator(0)])),
                ('cooling_capacity', models.IntegerField(default=0, help_text='Cooling capacity in BTU/hr', validators=[django.core.validators.MinValueValidator(0)])),
                ('network_capacity', models.IntegerField(default=0, help_text='Network capacity in Gbps', validators=[django.core.validators.MinValueValidator(0)])),
                ('ru_size', models.IntegerField(default=0, help_text='Rack units consumed (0 = not racked)', validators=[django.core.validators.MinValueValidator(0)])),
                ('position', models.IntegerField(blank=True, help_text='Starting RU position in rack (null = not racked)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rack', models.ForeignKey(blank=True, db_column='rack_id', help_text='Rack where this provider is installed (null = not racked)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='api.rack')),
                ('site', models.ForeignKey(db_column='site_id', on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='api.site')),
            ],
            options={
                'db_table': 'resource_providers',
                'ordering': ['site', 'type', 'name'],
                'indexes': [models.Index(fields=['site'], name='resource_pr_site_id_c54b77_idx'), models.Index(fields=['type'], name='resource_pr_type_982bfc_idx'), models.Index(fields=['rack'], name='resource_pr_rack_id_a87d1c_idx')],
            },
        ),
    ]
