# Generated by Django 5.2.8 on 2025-11-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_hardware_provider_device_group_resource_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='network_capacity',
        ),
        migrations.AlterField(
            model_name='provider',
            name='type',
            field=models.CharField(choices=[('power', 'Power'), ('cooling', 'Cooling')], db_index=True, max_length=20),
        ),
    ]
