# Generated by Django 5.2.8 on 2025-11-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_network_provider"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="provider",
            index=models.Index(fields=["site", "type"], name="provider_site_type_idx"),
        ),
        migrations.AddIndex(
            model_name="provider",
            index=models.Index(fields=["site", "name"], name="provider_site_name_idx"),
        ),
        migrations.AddIndex(
            model_name="provider",
            index=models.Index(fields=["rack", "position"], name="provider_rack_pos_idx"),
        ),
        migrations.AddIndex(
            model_name="rack",
            index=models.Index(fields=["site", "name"], name="rack_site_name_idx"),
        ),
        migrations.AddIndex(
            model_name="rackconfiguration",
            index=models.Index(fields=["site", "name"], name="rack_config_site_name_idx"),
        ),
        migrations.AddConstraint(
            model_name="provider",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ru_size__gt", 0),
                    models.Q(("ru_size", 0), ("rack__isnull", True), ("position__isnull", True)),
                    _connector="OR",
                ),
                name="provider_zero_rusize_not_racked",
            ),
        ),
        migrations.AddConstraint(
            model_name="provider",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("rack__isnull", True), ("position__isnull", True)),
                    models.Q(("rack__isnull", False), ("position__isnull", False)),
                    _connector="OR",
                ),
                name="provider_rack_position_together",
            ),
        ),
        migrations.AddConstraint(
            model_name="provider",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__isnull", True), ("position__gte", 1), _connector="OR"),
                name="provider_position_positive",
            ),
        ),
    ]
